
# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`


1. Import the numpy package under the name

In [1]:
import numpy as np

2. Create a null vector of size 10

In [3]:
null_v = np.zeros(10)
print(null_v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
hint: array[4]

In [10]:
(np.arange(10)==4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [12]:
(np.arange(10)==4)

array([False, False, False, False,  True, False, False, False, False,
       False])

5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
hint: reshape

In [14]:
x=np.arange(0,9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
np.reshape(x,(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)¶
hint: np.nonzero

In [14]:
a = np.array([1,2,0,0,4,0])
a

array([1, 2, 0, 0, 4, 0])

In [16]:
np.nonzero(a) #gives the coordenates of values that are not zero in the array

(array([0, 1, 4], dtype=int64),)

7. Create a 3x3 identity matrix (★☆☆)
hint: np.eye

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Create a 3x3x3 array with random values (★☆☆)
hint: np.random.random

In [19]:
np.random.random((3,3))

array([[0.32372984, 0.13647968, 0.18290562],
       [0.10102864, 0.5518302 , 0.35105178],
       [0.04576464, 0.01976975, 0.94828993]])

In [23]:
np.random.random((3,3,3))

array([[[0.56114955, 0.01514419, 0.70773573],
        [0.32058132, 0.28154709, 0.3587988 ],
        [0.3256614 , 0.38635494, 0.55059914]],

       [[0.4439411 , 0.67813282, 0.43094779],
        [0.65075071, 0.70858411, 0.03396184],
        [0.87526916, 0.41667953, 0.54200583]],

       [[0.32131349, 0.50683993, 0.1576133 ],
        [0.92811605, 0.45544201, 0.34654828],
        [0.55212725, 0.3671197 , 0.97960396]]])

9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
hint: min, max

In [29]:
np.random.seed(42)
b = np.random.random((10,10))
b

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
        0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998,
        0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041],
       [0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203,
        0.80839735, 0.30461377, 0.09767211, 0.68423303, 0.44015249],
       [0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998,
        0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446],
       [0.96958463, 0.77513282, 0.93949894, 0.89482735, 0.59789998,
        0.92187424, 0.0884925 , 0.19598286, 0.04522729, 0.32533033],
       [0.38867729, 0.27134903, 0.82873751, 0.35675333, 0.28093451,
        0.54269608, 0.14092422, 0.80219698, 0.07455064, 0.98688694],
       [0.77224477, 0.19871568, 0.0055221

In [38]:
np.random.seed(42)
np.random.random((10,10)).max()

0.9868869366005173

In [41]:
print(np.max( b ))
print(np.min(b))


0.9868869366005173
0.005522117123602399


10. Create a random vector of size 30 and find the mean value (★☆☆)
hint: mean

In [31]:
np.random.seed(42)
c = np.random.random(30)
c

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
       0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
       0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914,
       0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998,
       0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041])

In [32]:
np.mean(c)

0.43859727209743676

In [46]:
np.random.seed(42)
np.random.random(30).mean()

0.43859727209743676

11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
hint: np.diag

In [56]:
b=np.arange(1,5)
b

array([1, 2, 3, 4])

In [58]:
np.diag(b,k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [60]:
np.diag(1+np.arange(4), k =-1) # 'k='' is not necesary, k>0 for diagonals above the main diagonal, 
#k<0 for diagonals below the main diagonal.

#1+ so the values star in 1 not in 0

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [61]:
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

12. Normalize a 5x5 random matrix (★☆☆)
hint: (x -mean)/std

In [50]:
np.random.seed(1524)
d = np.random.random((5,5))
d

array([[0.94174746, 0.39105879, 0.05816787, 0.02507077, 0.53458217],
       [0.44231089, 0.69021013, 0.3084805 , 0.3634608 , 0.64434605],
       [0.29353533, 0.7384209 , 0.01085233, 0.55136738, 0.22354734],
       [0.54064204, 0.08773082, 0.25946603, 0.41612141, 0.50597117],
       [0.13981042, 0.76991768, 0.46417968, 0.82710643, 0.51305521]])

In [54]:
xb = np.mean(d)
xb

0.429646384350438

In [56]:
sigma = np.std(d)
sigma

0.2518964872166595

In [62]:
d_max= np.max(d)
d_min = np.min(d)

In [64]:
d= (d - d_min)/(d_max - d_min)
d

array([[ 1.06257691,  0.4270929 ,  0.04294325,  0.00474984,  0.59271608],
       [ 0.48623683,  0.77230772,  0.33179916,  0.39524536,  0.71938147],
       [ 0.31455272,  0.82794202, -0.01165795,  0.61208589,  0.23378795],
       [ 0.59970906,  0.07705833,  0.27523742,  0.45601468,  0.55969955],
       [ 0.13715717,  0.86428869,  0.51147298,  0.93028339,  0.5678744 ]])

13. How to find common values between two arrays? (★☆☆)¶
hint: np.intersect1d


np.intersect1d(array1, array2)

In [63]:
array1, array2 = np.arange(1,6), np.arange(3,8)
print(array1,array2)

[1 2 3 4 5] [3 4 5 6 7]


In [64]:
np.intersect1d(array1,array2)

array([3, 4, 5])

14. Create a random vector of size 10 and sort it (★★☆)
hint: sort

In [70]:
np.random.seed(77546)
e = np.random.random((10))
e

array([0.57954883, 0.88180274, 0.85104674, 0.44244095, 0.51484843,
       0.95682045, 0.87932914, 0.87057705, 0.14249652, 0.33547195])

In [71]:
np.sort(e)

array([0.14249652, 0.33547195, 0.44244095, 0.51484843, 0.57954883,
       0.85104674, 0.87057705, 0.87932914, 0.88180274, 0.95682045])

In [66]:
np.random.seed(42)
np.sort(np.random.random(10))

array([0.05808361, 0.15599452, 0.15601864, 0.37454012, 0.59865848,
       0.60111501, 0.70807258, 0.73199394, 0.86617615, 0.95071431])

15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
hint: argmax

In [69]:
np.random.seed(42)
array15=np.random.random(10)
array15

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [70]:
array15.argmax()

1

In [71]:
array15[1]

0.9507143064099162

In [72]:
array15[1]= 0
array15

array([0.37454012, 0.        , 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [72]:
np.random.seed(777777)
f = np.random.random((10))
f

array([0.99548984, 0.20044008, 0.64525236, 0.05201115, 0.30476065,
       0.31441259, 0.34411116, 0.06052971, 0.12114764, 0.08085325])

In [75]:
f[f.argmax()] = 0
f

array([0.        , 0.20044008, 0.64525236, 0.05201115, 0.30476065,
       0.31441259, 0.34411116, 0.06052971, 0.12114764, 0.08085325])

16. Subtract the mean of each row of a matrix (★★☆)
hint: mean(axis=,keepdims=)

In [74]:
np.random.seed(42)
array16 = np.random.random((3,3))
array16

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

In [76]:
array16.mean(axis=1)

array([0.68574946, 0.30355721, 0.50845826])

In [77]:
m_array16 = array16 - array16.mean(axis=1, keepdims=True)
m_array16

array([[-0.31120934,  0.26496485,  0.04624449],
       [ 0.29510127, -0.14753857, -0.14756269],
       [-0.45037464,  0.35771789,  0.09265676]])

17. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition

In [85]:
np.random.seed(42)
array17 = np.random.random((5))
array17

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [86]:
array17_sort = np.argsort(i)
array17_sort

array([4, 0, 3, 2, 1], dtype=int64)

In [97]:
n=3
array17[n:]

array([0.59865848, 0.15601864])

In [82]:
k = np.argpartition(j,2)
k

array([3, 4, 2, 0, 1], dtype=int64)

18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)
hint: np.where

In [98]:
l = np.arange(10)
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
np.where(l < 4,l,l*l)


array([ 0,  1,  2,  3, 16, 25, 36, 49, 64, 81])

In [92]:
np.random.seed(42)
array18 = np.random.randint(10,size=(5,3))
array18

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [93]:
array18_sqr= np.where(array18<4,array18,array18*array18)
array18_sqr

array([[36,  3, 49],
       [16, 36, 81],
       [ 2, 36, 49],
       [16,  3, 49],
       [49,  2, 25]])