
# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`


1. Import the numpy package under the name

In [4]:
import numpy as np

2. Create a null vector of size 10

In [6]:
null_v = np.zeros(10)
print(null_v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
hint: array[4]

In [10]:
(np.arange(10)==4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
hint: reshape

In [12]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)¶
hint: np.nonzero

In [14]:
a = np.array([1,2,0,0,4,0])
a

array([1, 2, 0, 0, 4, 0])

In [16]:
np.nonzero(a) #gives the coordenates of values that are not zero in the array

(array([0, 1, 4], dtype=int64),)

7. Create a 3x3 identity matrix (★☆☆)
hint: np.eye

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Create a 3x3x3 array with random values (★☆☆)
hint: np.random.random

In [23]:
np.random.random((3,3,3))

array([[[0.56114955, 0.01514419, 0.70773573],
        [0.32058132, 0.28154709, 0.3587988 ],
        [0.3256614 , 0.38635494, 0.55059914]],

       [[0.4439411 , 0.67813282, 0.43094779],
        [0.65075071, 0.70858411, 0.03396184],
        [0.87526916, 0.41667953, 0.54200583]],

       [[0.32131349, 0.50683993, 0.1576133 ],
        [0.92811605, 0.45544201, 0.34654828],
        [0.55212725, 0.3671197 , 0.97960396]]])

9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
hint: min, max

In [28]:
np.random.seed(333)
b = np.random.random((10,10))
b

array([[0.54329109, 0.72895073, 0.01688145, 0.3303388 , 0.36872182,
        0.04830367, 0.10453019, 0.09743752, 0.24540331, 0.87348935],
       [0.05161164, 0.06048134, 0.23874011, 0.20369919, 0.17453362,
        0.4153501 , 0.94173812, 0.46691528, 0.95997821, 0.99981377],
       [0.72631715, 0.48422867, 0.12686103, 0.10540475, 0.04226596,
        0.244131  , 0.07151706, 0.99556762, 0.20132616, 0.88245121],
       [0.24522681, 0.11543404, 0.59220196, 0.70826194, 0.13028934,
        0.11850709, 0.00372051, 0.56942472, 0.48184031, 0.34116267],
       [0.26471783, 0.34771782, 0.9207149 , 0.98316199, 0.97648642,
        0.0427551 , 0.80801819, 0.86668909, 0.51798327, 0.7153192 ],
       [0.19054784, 0.64362849, 0.54668746, 0.55958402, 0.19326741,
        0.32445955, 0.18190523, 0.61739294, 0.28793773, 0.1343628 ],
       [0.32677088, 0.17852022, 0.41733021, 0.37654918, 0.45613382,
        0.24486177, 0.70496897, 0.11983588, 0.3189468 , 0.77762613],
       [0.06439634, 0.99494058, 0.0934207

In [33]:
print(np.max( b ))
print(np.min(b))


0.9998137663042677
0.003720511157856099


10. Create a random vector of size 30 and find the mean value (★☆☆)
hint: mean

In [37]:
np.random.seed(70000)
c = np.random.random(30)
c

array([0.82010739, 0.09782832, 0.81567415, 0.4331293 , 0.90437766,
       0.29861264, 0.82434214, 0.52145497, 0.8174183 , 0.53615202,
       0.89423525, 0.37313058, 0.86599288, 0.03853851, 0.96446364,
       0.76663197, 0.96761053, 0.07583492, 0.40560189, 0.0902261 ,
       0.95124847, 0.9935168 , 0.95612384, 0.31139517, 0.39496594,
       0.30627315, 0.54239328, 0.28961745, 0.0337392 , 0.94811169])

In [38]:
np.mean(c)

0.5746249381544449

11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
hint: np.diag

In [48]:
np.diag(1+np.arange(4), k =-1) # 'k='' is not necesary, k>0 for diagonals above the main diagonal, 
#k<0 for diagonals below the main diagonal.

#1+ so the values star in 1 not in 0

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

12. Normalize a 5x5 random matrix (★☆☆)
hint: (x -mean)/std

In [50]:
np.random.seed(1524)
d = np.random.random((5,5))
d

array([[0.94174746, 0.39105879, 0.05816787, 0.02507077, 0.53458217],
       [0.44231089, 0.69021013, 0.3084805 , 0.3634608 , 0.64434605],
       [0.29353533, 0.7384209 , 0.01085233, 0.55136738, 0.22354734],
       [0.54064204, 0.08773082, 0.25946603, 0.41612141, 0.50597117],
       [0.13981042, 0.76991768, 0.46417968, 0.82710643, 0.51305521]])

In [54]:
xb = np.mean(d)
xb

0.429646384350438

In [56]:
sigma = np.std(d)
sigma

0.2518964872166595

In [62]:
d_max= np.max(d)
d_min = np.min(d)

In [64]:
d= (d - d_min)/(d_max - d_min)
d

array([[ 1.06257691,  0.4270929 ,  0.04294325,  0.00474984,  0.59271608],
       [ 0.48623683,  0.77230772,  0.33179916,  0.39524536,  0.71938147],
       [ 0.31455272,  0.82794202, -0.01165795,  0.61208589,  0.23378795],
       [ 0.59970906,  0.07705833,  0.27523742,  0.45601468,  0.55969955],
       [ 0.13715717,  0.86428869,  0.51147298,  0.93028339,  0.5678744 ]])

13. How to find common values between two arrays? (★☆☆)¶
hint: np.intersect1d


np.intersect1d(array1, array2)

14. Create a random vector of size 10 and sort it (★★☆)
hint: sort

In [70]:
np.random.seed(77546)
e = np.random.random((10))
e

array([0.57954883, 0.88180274, 0.85104674, 0.44244095, 0.51484843,
       0.95682045, 0.87932914, 0.87057705, 0.14249652, 0.33547195])

In [71]:
np.sort(e)

array([0.14249652, 0.33547195, 0.44244095, 0.51484843, 0.57954883,
       0.85104674, 0.87057705, 0.87932914, 0.88180274, 0.95682045])

15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
hint: argmax

In [72]:
np.random.seed(777777)
f = np.random.random((10))
f

array([0.99548984, 0.20044008, 0.64525236, 0.05201115, 0.30476065,
       0.31441259, 0.34411116, 0.06052971, 0.12114764, 0.08085325])

In [75]:
f[f.argmax()] = 0
f

array([0.        , 0.20044008, 0.64525236, 0.05201115, 0.30476065,
       0.31441259, 0.34411116, 0.06052971, 0.12114764, 0.08085325])

16. Subtract the mean of each row of a matrix (★★☆)
hint: mean(axis=,keepdims=)

In [79]:
np.random.seed(12345689)
g = np.random.random((3,3))
g

array([[0.24095773, 0.12145201, 0.50082199],
       [0.49083586, 0.94609061, 0.0919834 ],
       [0.50555674, 0.80277107, 0.86662215]])

In [81]:
h = g - g.mean(axis=1, keepdims=True)
h

array([[-0.04678618, -0.1662919 ,  0.21307808],
       [-0.01880076,  0.43645399, -0.41765323],
       [-0.21942658,  0.07778775,  0.14163883]])

17. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition

In [88]:
np.random.seed(48353854)
i = np.random.random((5))
i

array([0.45727946, 0.73408585, 0.39878132, 0.0895491 , 0.2439955 ])

In [89]:
j = np.argsort(i)
j

array([3, 4, 2, 0, 1], dtype=int64)

In [93]:
k = np.argpartition(j,3)
k

array([3, 4, 2, 0, 1], dtype=int64)

18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)
hint: np.where

In [98]:
l = np.arange(10)
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
np.where(l < 4,l,l*l)


array([ 0,  1,  2,  3, 16, 25, 36, 49, 64, 81])